### ISSUE TITLE
Cannot construct eval paths

### ISSUE THREAD

**Issue by poorboy44** [intel-isl/FreeViewSynthesis#13]
I tried to follow the instructions in the README but can't get the code to run. Here's what I did:

1) updated config.py to point to the downloaded data:

```
dtu_root ="/home/poorboy44/Downloads/free_view_synthesis_data/own_data"
tat_root ="/home/poorboy44/Downloads/free_view_synthesis_data/tat_data"
colmap_bin_path ="/usr/local/bin/colmap"
lpips_root = None
```

I was not sure what `lpips_root` is. Also the last line in config.py says `path/to/colmap_tat` but I don't know what that means so I commented it out.  
```
# TODO: adjust path
#tat_root = Path("/path/to/colmap_tat/")
```

Then I run the command listed in the README from the experiments directoryr:
```
(py36_free_view_synthesis) poorboy44@poorboy44-XPS-8930:~/FreeViewSynthesis/exp$ python exp.py --net rnn_vgg16unet3_gruunet4.64.3 --cmd eval --iter last --eval-dsets tat-subseq --eval-scale 0.5
```

But I get this error:
```
[2020-12-07/13:28/INFO/exp] Create eval datasets
Traceback (most recent call last):
  File "exp.py", line 467, in <module>
    worker.do(args, worker_objects)
  File "../co/mytorch.py", line 423, in do
    self.do_cmd(args, worker_objects)
  File "../co/mytorch.py", line 411, in do_cmd
    worker_objects, iters=args.iter, net_root=args.eval_net_root
  File "../co/mytorch.py", line 583, in eval_iters
    eval_sets = self.get_eval_sets()
  File "exp.py", line 240, in get_eval_sets
    dset = self.get_eval_set_tat(dset, "subseq")
  File "exp.py", line 205, in get_eval_set_tat
    dense_dir = config.tat_root / dset / "dense"
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

So, this line doesn't seem to be valid Python or there is an assumption about a different format in the path?
```
 dense_dir = config.tat_root / dset / "dense"
```
 I am using Python 3.6. Is there an assumption that the user is using another Python version where this syntax is valid? 

I'm really interested in this project and looking forward to resolving these issues.
Scotty

**Comment by griegler** [comment]
Try changing 

```
tat_root ="/home/poorboy44/Downloads/free_view_synthesis_data/tat_data"
```

to 

```
tat_root =Path("/home/poorboy44/Downloads/free_view_synthesis_data/tat_data")
```
