### ISSUE TITLE
Windows Build - DLL load failed

### ISSUE THREAD

**Issue by Kait0** [intel-isl/FreeViewSynthesis#9]
Hi,

I am trying to get this repository to run on a Windows 10 machine.
Maybe unsurprisingly (since the platform isn't officially supported) I ran into some issues.

I wanted to ask if there is any plan to support the plattform or if somebody has an idea on how to resolve the error.

The error I got stuck upon was that python was complaining about missing DLLs when I ran the program with the default options: 
python -v exp.py --net rnn_vgg16unet3_gruunet4.64.3 --cmd eval --iter last --eval-dsets tat-subseq --eval-scale 0.5
(with verbose output)
> Traceback (most recent call last):
> 
>   File "exp.py", line 8, in <module>
>     import dataset
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\Users\admin\Ordnung\Studium\Forschungsprojekt\FreeViewSynthesis\exp\dataset.py", line 8, in <module>
>     import ext
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "..\ext\__init__.py", line 1, in <module>
>     from . import preprocess
>   File "<frozen importlib._bootstrap>", line 1035, in _handle_fromlist
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "..\ext\preprocess\__init__.py", line 1, in <module>
> from .preprocess import *
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 583, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 1043, in create_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> ImportError: DLL load failed: The specified module could not be found.

Since I have no idea why DLL is reffered to (and don't know how to find it out) I got stuck here.
I tested it two different Windows machines so it does not seem to be an issue related to DLLs that should normally be there.

To get the preprocess module to compile in the first place I had to do some changes. I don't think they are related to this issue but I wanted to list them for completeness:

- When I ran the cmake PkgConfig couldn't find my Eigen installation.
Since I found no straigthforward way to tell pkgconfig where it was I just ditched it and linked the Eigen via an Environment variable:
```
find_package( PkgConfig )
#pkg_check_modules( EIGEN3 REQUIRED eigen3 )
include_directories( $ENV{EIGEN3_INCLUDE_DIRS} )
```

- When I compiled the resulting project in Visual Stuido 2019 the line 37 in common.h threw a compiler error:

> template <typename T>
> py::array_t<T> create_array1(const std::vector<T>& data)
> {
> ...
>     return py::array_t<T>({data.size()}, new_data, free_data);
> }

The Visual Studio compiler complained about something related to narrowing conversion.
I just removed the curly brackets around the data.size() to "fix" that.

I moved the resulting 3 files preprocess.exp, preprocess.lib and preprocess.cp37-win_amd64.pyd to ...\ext\preprocess so that the program could find them.

**Comment by Kait0** [comment]
I managed to successfully run the evaluation script now.
With the help of the program ProcessMonitor I could see that the DLL missing above was simply the preprocess.cp37-win_amd64.pyd file.
The programm was looking for it in path/ext/preprocess
Where path where a bunch of different paths from the executed files directories to environment variables.
Unfortunately the project root directory was not among them (maybe because there was no execute file in there?) so the project ended up looking for the files in areas like:
path_to_FVS/ext/ext/preprocess/

I'm not quite sure why this is the case but I was able to work around that by simply copying the files to this location.





In case somebody else tries to run the repository on Windows here is a little guide on what I had to change to run the program on Windows 10:

0. Clone and initialize the git and install the mentioned python libraries:
git clone https://github.com/intel-isl/FreeViewSynthesis.git
cd FreeViewSynthesis
git submodule update --init --recursive

1. In ext/preprocess/CMakeLists.txt change the following two lines:
Uncomment this line:
#pkg_check_modules( EIGEN3 REQUIRED eigen3 )
Add the ENV in this one.
include_directories( $ENV{EIGEN3_INCLUDE_DIRS} )

Download the Eigen library source code and store it somewhere (you don't need to compile it).
Than create an Environment Variable called EIGEN3_INCLUDE_DIRS. 
As value you give it the path to the installation directory of the Eigen files you just downloaded.

This way the CMake will be able to find you Eigen installation.

2. Go to /ext/preprocess/ open a command line and run the CMake command as usual:
cmake -DCMAKE_BUILD_TYPE=Release .

3. If your C++ compiler is Visual Studio this will create Visual Studio projects in the folder.
Open reprocess.sln
Goto the file common.h in the same folder.
In the function create_array1 line 37 you need to remove the curly brackets {} in the return statement.
Otherwise this might lead to compiler errors.

return py::array_t<T>({data.size()}, new_data, free_data);  ----> return py::array_t<T>(data.size(), new_data, free_data); 

4. Build the reprocess.sln project (via ALL_BUILD)
Make sure the build is set to release and the correct plattfor (x64 for me)

5. Build the pybind11.sln project in the subfolder Pybind11
(This step might not be needed)

6. You now should have generated 3 files in the folder /ext/preprocess/Release (or similar)
They are called preprocess.lib, preprocess.exp, preprocess.cp37-win_amd64.pyd
Copy these files into the folders path_to_FVS/ext/preprocess/
and path_to_FVS/ext/ext/preprocess/
The second folder you have to create first.
This is a workaround because the project somehow looks for the files in a path with an extra ext.

7. Download the Tanks and temples dataset and extract is somewhere. We call that folder path_to_FVS/data for now.
(This will take some time it's 16GB big.)

8. In path_to_FVS/config.py change the tat_root path to path_to_FVS/data.
Make sure you replace all backslashes \ with slashes / in the path.

9. In path_to_FVS/co/mytorch.py go to the function format_err_str and change it from 
def format_err_str(self, errs, div=1):

```
> def format_err_str(self, errs, div=1):
> 	err_list = []
> 	for v in errs.values():
> 		if isinstance(v, (list, np.ndarray)):
> 			err_list.extend(v.ravel())
> 		else:
> 			err_list.append(v)
> 	...
>
``` 	

to
	

```
> def format_err_str(self, errs, div=1):
> 	err_list = []
> 	for v in errs.values():
> 		#if isinstance(v, (list, np.ndarray)):
> 		if isinstance(v, (np.ndarray)):
> 			err_list.extend(v.ravel())
> 		elif isinstance(v, (list)):
> 			err_list.extend(np.array(v).ravel())
> 		else:
> 			err_list.append(v)
>...
``` 		

This seems to be a bug in the current version, because if v is a list than "isinstance(v, (list, np.ndarray)):" will return true and v.ravel() will crash.
Might also be related to library versions.


10. Download the pretrained networks if you want:
https://storage.googleapis.com/isl-datasets/FreeViewSynthesis/experiments.tar.gz
and extract it with something like 7-Zip.
Make sure to download the file to the root directly than after extracting with 7-zip the files are already in the right locations.

11. Now you should be able to run the evaluation script in path_to_FVS/exp:

> python exp.py --net rnn_vgg16unet3_gruunet4.64.3 --cmd eval --iter last --eval-dsets tat-subseq --eval-scale 0.5

The script will try to run the network on the GPU. This requires that you installed pytorch togheter with CUDA.
Also the network is quite large. I tested it with 2 different machines. On my 4GB GPU I got an "Out of Memory error", on my 8GB GPU it worked.
In case you don't have a good enough GPU memory you can (in config.py) change the variables 
eval_device and train_device to "cpu"
Than the network will run on the CPU.
I wouldn't recommend this since the programm will run rougly 30x slower than.


Hope this help :)
